"""
portfolio_manager.py
Generates trading signals from weekly report conclusions.
Strictly avoids look-ahead bias: signals are generated on signal_date (T)
and recorded as pending orders for execution on T+1.
禁止未来函数（no look-ahead bias）
"""

import json
import os
from datetime import datetime, timedelta
from typing import List, Dict, Any

PORTFOLIO_DIR = "portfolio"
PENDING_ORDERS_FILE = os.path.join(PORTFOLIO_DIR, "pending_orders.json")
WEEKLY_SIGNALS_FILE = os.path.join(PORTFOLIO_DIR, "weekly_signals.json")

def load_weekly_signals(report_date: str) -> List[Dict[str, Any]]:
    """
    Load signals from weekly_signals.json for the given report_date.
    This file is generated by weekly_report.py on Mondays.
    禁止未来函数（no look-ahead bias）
    """
    if not os.path.exists(WEEKLY_SIGNALS_FILE):
        print(f"[portfolio_manager] No weekly signals file found for {report_date}")
        return []
    with open(WEEKLY_SIGNALS_FILE, "r", encoding="utf-8") as f:
        all_signals = json.load(f)
    # Filter signals for the given date (the file may contain multiple dates)
    signals = [s for s in all_signals if s.get("date") == report_date]
    return signals

def generate_pending_orders(report_date: str) -> None:
    """
    Generate pending orders from weekly signals for the given report_date.
    Orders are saved to pending_orders.json with signal_date = report_date.
    Execution will happen on the next trading day (T+1).
    禁止未来函数（no look-ahead bias）
    """
    signals = load_weekly_signals(report_date)
    pending_orders = []
    for sig in signals:
        ticker = sig.get("ticker")
        action = sig.get("action", "hold")
        reason = sig.get("reason", "")
        target_weight = sig.get("target_weight", 0.0)
        if action in ("buy", "sell"):
            order = {
                "ticker": ticker,
                "action": action,
                "signal_date": report_date,
                "reason": reason,
                "target_weight": target_weight,
                "status": "pending"
            }
            pending_orders.append(order)
    # Save to file
    os.makedirs(PORTFOLIO_DIR, exist_ok=True)
    with open(PENDING_ORDERS_FILE, "w", encoding="utf-8") as f:
        json.dump(pending_orders, f, ensure_ascii=False, indent=2)
    print(f"[portfolio_manager] Generated {len(pending_orders)} pending orders for {report_date}")

if __name__ == "__main__":
    import sys
    report_date = sys.argv[1] if len(sys.argv) > 1 else datetime.now().strftime("%Y-%m-%d")
    generate_pending_orders(report_date)
